2025-05-12 18:18:51 error: Error no capturado: _this_1.callback is not a function
2025-05-19 13:38:44 error: Error al conectar a las bases de datos: Access denied for user 'root'@'localhost' (using password: YES)
2025-05-19 13:39:15 error: Error al conectar a las bases de datos: Unknown database 'ws_pedido_db'
